# VacationPy
----

#### Note
* Instructions have been included for each segment. You do not have to follow them exactly, but they are included to help you think through the steps.

In [1]:
# Dependencies and Setup


import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import requests
import gmaps
import os


# Import API key
from api_keys import g_key
print(g_key)

AIzaSyDvlqBLINtFSxPxZK2A-HAetCLAazJzcAY

### Store Part I results into DataFrame
* Load the csv exported in Part I to a DataFrame

In [2]:
weather_data = pd.read_csv('wetherpycsv.csv')
weather_data

,Unnamed: 0,city,Lattitude,temp,Humidity,Cloudiness,WindSpeed,longitude
0,0,bubaque,11.28,25.29,73,69,4.39,-15.83
1,1,butaritari,3.07,28.86,79,97,10.28,172.79
2,2,port macquarie,-31.43,30.66,51,13,6.70,152.92
3,3,rikitea,-23.12,26.60,78,43,2.34,-134.97
4,4,surt,31.21,10.98,85,0,1.74,16.59
...,...,...,...,...,...,...,...,...
544,544,abha,18.22,12.48,81,40,3.60,42.51
545,545,haileybury,47.45,-7.00,92,90,5.70,-79.64
546,546,sabha,27.04,12.56,36,85,4.62,14.43
547,547,qasigiannguit,68.82,-14.00,60,100,4.60,-51.19
548,548,wagar,16.15,17.48,69,33,1.95,36.20

In [3]:
weather_data12= weather_data.drop(columns="Unnamed: 0" )
weather_data12

,city,Lattitude,temp,Humidity,Cloudiness,WindSpeed,longitude
0,bubaque,11.28,25.29,73,69,4.39,-15.83
1,butaritari,3.07,28.86,79,97,10.28,172.79
2,port macquarie,-31.43,30.66,51,13,6.70,152.92
3,rikitea,-23.12,26.60,78,43,2.34,-134.97
4,surt,31.21,10.98,85,0,1.74,16.59
...,...,...,...,...,...,...,...
544,abha,18.22,12.48,81,40,3.60,42.51
545,haileybury,47.45,-7.00,92,90,5.70,-79.64
546,sabha,27.04,12.56,36,85,4.62,14.43
547,qasigiannguit,68.82,-14.00,60,100,4.60,-51.19
548,wagar,16.15,17.48,69,33,1.95,36.20

### Humidity Heatmap
* Configure gmaps.
* Use the Lat and Lng as locations and Humidity as the weight.
* Add Heatmap layer to map.

In [4]:

gmaps.configure(api_key=g_key)


locations = weather_data12[["Lattitude", "longitude"]].astype(float)
Humidity = weather_data12["Humidity"].astype(float)





fig = gmaps.figure()




heat_layer = gmaps.heatmap_layer(locations, weights=Humidity, 
                                 dissipating=False, max_intensity=100,
                                 point_radius = 1)

fig.add_layer(heat_layer)
fig

Figure(layout=FigureLayout(height='420px'))

### Create new DataFrame fitting weather criteria
* Narrow down the cities to fit weather conditions.
* Drop any rows will null values.

In [5]:
maxtemp = weather_data12[weather_data12.temp <= 29 ]
idealtemp = maxtemp[maxtemp.temp >= 15 ]
idawind= idealtemp[idealtemp.WindSpeed <= 10 ]
Idial =idawind[idawind.Cloudiness <=0]
Idial

,city,Lattitude,temp,Humidity,Cloudiness,WindSpeed,longitude
18,saint-pierre,-21.34,26.11,57,0,5.10,55.48
57,luderitz,-26.65,16.00,63,0,2.60,15.16
62,guerrero negro,27.98,15.45,78,0,1.20,-114.06
75,nouadhibou,20.93,16.00,72,0,7.20,-17.03
84,chuy,-33.70,15.03,78,0,1.47,-53.46
158,taoudenni,22.68,17.56,21,0,3.92,-3.98
169,vallenar,-28.57,16.11,80,0,0.91,-70.76
189,norton,-17.88,16.00,82,0,4.47,30.70
204,rangapara,26.82,17.21,48,0,2.19,92.65
212,constitucion,-35.33,15.59,80,0,3.36,-72.42
238,doka,13.52,20.94,36,0,2.14,35.77
249,vega de alatorre,20.03,23.08,86,0,4.92,-96.63
270,tezu,27.92,19.52,31,0,1.96,96.17
327,saint-joseph,-21.37,26.10,57,0,5.10,55.62
359,shahdadkot,27.85,19.12,36,0,0.86,67.91
365,gaurnadi,22.97,24.92,33,0,1.49,90.23
374,salalah,17.02,17.00,21,0,7.70,54.09
383,coahuayana,18.73,18.94,43,0,2.27,-103.68
384,doha,25.29,15.63,67,0,2.60,51.53
424,colima,19.17,17.89,76,0,1.51,-104.00
439,saint-louis,16.33,19.00,37,0,1.00,-15.00
446,myanaung,18.28,28.55,24,0,0.67,95.32
461,san patricio,19.22,23.32,74,0,4.41,-104.70
470,ampanihy,-24.70,27.77,65,0,1.33,44.75
489,sonoita,31.85,15.56,26,0,3.29,-112.83
543,akyab,20.15,22.44,45,0,3.36,92.90

### Hotel Map
* Store into variable named `hotel_df`.
* Add a "Hotel Name" column to the DataFrame.
* Set parameters to search for hotels with 5000 meters.
* Hit the Google Places API for each city's coordinates.
* Store the first Hotel result into the DataFrame.
* Plot markers on top of the heatmap.

In [6]:
Idial["Hotel"] = ""
hotel=Idial
hotel

/Users/blakewilfong/opt/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  """Entry point for launching an IPython kernel.

,city,Lattitude,temp,Humidity,Cloudiness,WindSpeed,longitude,Hotel
18,saint-pierre,-21.34,26.11,57,0,5.10,55.48,
57,luderitz,-26.65,16.00,63,0,2.60,15.16,
62,guerrero negro,27.98,15.45,78,0,1.20,-114.06,
75,nouadhibou,20.93,16.00,72,0,7.20,-17.03,
84,chuy,-33.70,15.03,78,0,1.47,-53.46,
158,taoudenni,22.68,17.56,21,0,3.92,-3.98,
169,vallenar,-28.57,16.11,80,0,0.91,-70.76,
189,norton,-17.88,16.00,82,0,4.47,30.70,
204,rangapara,26.82,17.21,48,0,2.19,92.65,
212,constitucion,-35.33,15.59,80,0,3.36,-72.42,
238,doka,13.52,20.94,36,0,2.14,35.77,
249,vega de alatorre,20.03,23.08,86,0,4.92,-96.63,
270,tezu,27.92,19.52,31,0,1.96,96.17,
327,saint-joseph,-21.37,26.10,57,0,5.10,55.62,
359,shahdadkot,27.85,19.12,36,0,0.86,67.91,
365,gaurnadi,22.97,24.92,33,0,1.49,90.23,
374,salalah,17.02,17.00,21,0,7.70,54.09,
383,coahuayana,18.73,18.94,43,0,2.27,-103.68,
384,doha,25.29,15.63,67,0,2.60,51.53,
424,colima,19.17,17.89,76,0,1.51,-104.00,
439,saint-louis,16.33,19.00,37,0,1.00,-15.00,
446,myanaung,18.28,28.55,24,0,0.67,95.32,
461,san patricio,19.22,23.32,74,0,4.41,-104.70,
470,ampanihy,-24.70,27.77,65,0,1.33,44.75,
489,sonoita,31.85,15.56,26,0,3.29,-112.83,
543,akyab,20.15,22.44,45,0,3.36,92.90,

In [7]:
params = {
    "radius": 50000,
    "types": "Hotel",
    "keyword": "Hotels",
    "key": g_key 
}



for index, row in Idial.iterrows():
    lat = row["Lattitude"]
    lng = row["longitude"]
    params["location"] = f"{lat},{lng}"
    base_url = "https://maps.googleapis.com/maps/api/place/nearbysearch/json"
    name_address = requests.get(base_url, params=params)
    name_address = name_address.json()
    try:
        hotel.loc[index, "Hotel"] = name_address["results"][0]["name"]
    except (KeyError, IndexError):
        print("Missing field/result... skipping.")

/Users/blakewilfong/opt/anaconda3/lib/python3.7/site-packages/pandas/core/indexing.py:494: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  self.obj[item] = s

Missing field/result... skipping.
Missing field/result... skipping.

In [10]:
hotel

,city,Lattitude,temp,Humidity,Cloudiness,WindSpeed,longitude,Hotel
18,saint-pierre,-21.34,26.11,57,0,5.10,55.48,Palm Hotel & Spa
57,luderitz,-26.65,16.00,63,0,2.60,15.16,Obelix Guesthouse
62,guerrero negro,27.98,15.45,78,0,1.20,-114.06,"Casa Laguna, Bed & Breakfast"
75,nouadhibou,20.93,16.00,72,0,7.20,-17.03,HOtel Tasiast
84,chuy,-33.70,15.03,78,0,1.47,-53.46,Hotel Parque OceÃ¡nico
158,taoudenni,22.68,17.56,21,0,3.92,-3.98,
169,vallenar,-28.57,16.11,80,0,0.91,-70.76,Hotel Origenes
189,norton,-17.88,16.00,82,0,4.47,30.70,Meikles Hotel
204,rangapara,26.82,17.21,48,0,2.19,92.65,Baligara Eco Camp
212,constitucion,-35.33,15.59,80,0,3.36,-72.42,Hotel Playa El Cable
238,doka,13.52,20.94,36,0,2.14,35.77,
249,vega de alatorre,20.03,23.08,86,0,4.92,-96.63,Hotel Villas ARCON
270,tezu,27.92,19.52,31,0,1.96,96.17,Dibang Valley Jungle Camp
327,saint-joseph,-21.37,26.10,57,0,5.10,55.62,Palm Hotel & Spa
359,shahdadkot,27.85,19.12,36,0,0.86,67.91,Sambara Inn
365,gaurnadi,22.97,24.92,33,0,1.49,90.23,Hotel Grand Park Barisal
374,salalah,17.02,17.00,21,0,7.70,54.09,Salalah Rotana Resort
383,coahuayana,18.73,18.94,43,0,2.27,-103.68,Hotel Brisas De Verano
384,doha,25.29,15.63,67,0,2.60,51.53,"Marsa Malaz Kempinski, The Pearl - Doha"
424,colima,19.17,17.89,76,0,1.51,-104.00,BarcelÃ³ Karmina
439,saint-louis,16.33,19.00,37,0,1.00,-15.00,Gite d'Etape Keur Ninon
446,myanaung,18.28,28.55,24,0,0.67,95.32,Golden Royal Guest House
461,san patricio,19.22,23.32,74,0,4.41,-104.70,BarcelÃ³ Karmina
470,ampanihy,-24.70,27.77,65,0,1.33,44.75,Angora Hotel
489,sonoita,31.85,15.56,26,0,3.29,-112.83,Hotel Excelsior
543,akyab,20.15,22.44,45,0,3.36,92.90,Shwe Thazin Hotel

In [11]:
# NOTE: Do not change any of the code in this cell

# Using the template add the hotel marks to the heatmap
info_box_template = """
<dl>
<dt>Name</dt><dd>{Hotel}</dd>
<dt>City</dt><dd>{city}</dd>

</dl>
"""
# Store the DataFrame Row
# NOTE: be sure to update with your DataFrame name
hotel_info = [info_box_template.format(**row) for index, row in hotel.iterrows()]
locations = hotel[["Lattitude", "longitude"]]

In [12]:
# Add marker layer ontop of heat map
markers = gmaps.marker_layer(locations,hotel_info)
    
fig.add_layer(markers)
fig

# Display Map

Figure(layout=FigureLayout(height='420px'))